language: python

python:
  - 3.5
  - 3.6

script:
  - python setup.py test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    dev: $HEROKU_DEV_APP
    master: $HEROKU_PRO_APP
  on:
    python: 3.6
